services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:5.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  spark-master:
    image: apache/spark:latest
    working_dir: /spark
    command: sleep 999999
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./scripts:/scripts
      - C:/Users/henri/OneDrive/Desktop/Projetos/teste_engenheiro_economia/xmls:/xmls
      - C:/Users/henri/OneDrive/Desktop/Projetos/teste_engenheiro_economia/airflow:/airflow

  airflow:
    image: apache/airflow:2.8.0
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    ports:
      - "8888:8080"
    volumes:
      - C:/Users/henri/OneDrive/Desktop/Projetos/teste_engenheiro_economia/airflow/dags:/opt/airflow/dags
      - C:/Users/henri/OneDrive/Desktop/Projetos/teste_engenheiro_economia/airflow/logs:/opt/airflow/logs
    depends_on:
      - postgres
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@airflow.com &&
               airflow webserver"